//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBSREQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BBSREQUEST()
        {
            this.REQUEST_PRODUCT = new HashSet<REQUEST_PRODUCT>();
            this.TESTS = new HashSet<BBSTEST>();
        }
    
        public string ACCESSNUMBER { get; set; }
        public double REQCREATIONDATE { get; set; }
        public string REDACCNUM { get; set; }
        public string PATNUMBER { get; set; }
        public string DOCCODE { get; set; }
        public Nullable<double> DOCCREDATE { get; set; }
        public string LOCCODE { get; set; }
        public Nullable<double> LOCCREDATE { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<System.DateTime> REQDATE { get; set; }
        public Nullable<byte> REQSTATUS { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        public Nullable<System.DateTime> REQUIREDDATE { get; set; }
        public Nullable<byte> REQURGENT { get; set; }
        public Nullable<int> SAMPLEID { get; set; }
        public string LINKACCESSNUMBER { get; set; }
        public Nullable<double> LINKREQCREATIONDATE { get; set; }
        public Nullable<int> RFTID { get; set; }
        public Nullable<byte> RESPRODCOMPLETED { get; set; }
        public Nullable<int> HOSPITID { get; set; }
        public Nullable<System.DateTime> BGMISMATCHDATE { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual BBSPATIENT PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_PRODUCT> REQUEST_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BBSTEST> TESTS { get; set; }
    }
}
