//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICT_TESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICT_TESTS()
        {
            this.TESTS = new HashSet<TEST>();
        }
    
        public string TESTCODE { get; set; }
        public double TESTCREDATE { get; set; }
        public string TESTTEXT { get; set; }
        public Nullable<byte> RESTYPE { get; set; }
        public Nullable<byte> UPDATEPATDEF { get; set; }
        public Nullable<short> TRECOLUMN { get; set; }
        public Nullable<byte> RESDOUBLEENTRY { get; set; }
        public Nullable<short> HISTCOLUMN { get; set; }
        public string FULLTEXT { get; set; }
        public Nullable<byte> ALLOWSAMPLERECEPTION { get; set; }
        public Nullable<byte> STANDALONE { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST> TESTS { get; set; }
    }
}
