//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICT_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DICT_PRODUCTS()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public string PRODCODE { get; set; }
        public double PRODCREDATE { get; set; }
        public string PRODTEXT { get; set; }
        public Nullable<byte> BATCHPRODUCT { get; set; }
        public Nullable<byte> NORHESUS { get; set; }
        public Nullable<int> CONSDURATION { get; set; }
        public Nullable<int> REPORTCOL { get; set; }
        public string FAMCODE { get; set; }
        public Nullable<double> FAMCREDATE { get; set; }
        public string BARCODE { get; set; }
        public Nullable<double> MANAGEREQ { get; set; }
        public Nullable<byte> CHECKCOMPAT { get; set; }
        public string FULLTEXT { get; set; }
        public Nullable<byte> MANYLABELS { get; set; }
        public Nullable<byte> STRENGTH { get; set; }
        public Nullable<byte> ABSVALIDITY { get; set; }
        public Nullable<int> MAXOUTOFFRIDGE { get; set; }
        public Nullable<byte> USEDONDATE { get; set; }
        public string XMPANELCODE { get; set; }
        public Nullable<int> DEVICEID { get; set; }
        public Nullable<byte> MAXPRODNUMLEN { get; set; }
        public Nullable<byte> MINPRODNUMLEN { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
