//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modification
    {
        public string modification_code { get; set; }
        public string header { get; set; }
        public string description { get; set; }
        public string mod_products { get; set; }
        public string notes { get; set; }
        public string indication { get; set; }
        public string text { get; set; }
        public string image { get; set; }
    }
}
