//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NoticeID { get; set; }
        public int CartID { get; set; }
        public int CategoryId { get; set; }
        public string NoticeText { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Category Category { get; set; }
    }
}
