//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Info
    {
        public string code { get; set; }
        public string prod_bloodline { get; set; }
        public string prodname_abr { get; set; }
        public string prodname_full { get; set; }
        public string prod_notes { get; set; }
        public string storage { get; set; }
        public string shelflife { get; set; }
        public string transport { get; set; }
        public string prod_description { get; set; }
        public string indications { get; set; }
        public string contraindication { get; set; }
        public string dosage { get; set; }
        public string test_header { get; set; }
        public string testing { get; set; }
        public string sample_requirement_L1 { get; set; }
        public string sample_requirement_L2 { get; set; }
        public string modification { get; set; }
        public string table_title { get; set; }
        public string table { get; set; }
        public string administration { get; set; }
        public string adverse_reactions { get; set; }
        public string pdf_link { get; set; }
        public string image1_link { get; set; }
        public string image2_link { get; set; }
    }
}
