//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodLineV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_brief
    {
        public string CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CONTENTS { get; set; }
        public string VOLUME { get; set; }
        public string RECOMMEDED_DOSAGE { get; set; }
        public string ADDITIONAL_REQUIREMENTS { get; set; }
    }
}
